version: '3'

services:
  blockchain:
    build:
      context: ./blockchain_py
      dockerfile: ./Dockerfile
    environment:
      - PORT=3000
      - DEBUG=1
    ports:
      - "3000:3000"
    volumes:
      - ./blockchain_py:/code